build:
  stage: build
  image: node:$nodeversion
  script:
    - node --version
    - npm ci
    - npm run build --if-present
    - npm test
  parallel:
    matrix:
      - nodeversion: [12,14,16]
  artifacts:
    paths:
      - coverage/lcov-report
pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv coverage/lcov-report public
  artifacts:
    paths:
      - public


