version: "3.8"
services:
  jenkins:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      BUILD_URL: http://localhost:8080/
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
